filmer() {
    mkdir "Action"
    mkdir "Adventure"
    mkdir "Animation"
    mkdir "Biography"
    mkdir "Comedy"
    mkdir "Crime"
    mkdir "Documentary"
    mkdir "Drama"
    mkdir "Fantasy"
    mkdir "History"
    mkdir "Horror"
    mkdir "Musical"
    mkdir "Mystery"
    mkdir "Romance"
    mkdir "Science Fiction"
    mkdir "Superhero"
    mkdir "Thriller"
    mkdir "Western"
}
